language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
  - node_modules
before_script:
  - chmod 0777 ./node_modules/.bin/jest
script:
  - npm install
  - npm test
after_success:
  - "coveralls"
