export const CLEAR_ERROR = "CLEAR_ERROR";
export const ADD_RESPONSE_MESSAGE = "ADD_RESPONSE_MESSAGE";

// action types for business componet
export const REGISTER_BUSINESS_SUCCESS = "REGISTER_BUSINESS_SUCCESS";
export const FETCH_ALL_BUSINESSES_SUCCESS = "FETCH_ALL_BUSINESSES_SUCCESS";
export const FETCH_ALL_BUSINESSES_FAIL = "FETCH_ALL_BUSINESSES_FAIL";
export const FETCH_BUSINESSES_BY_USER_ID_SUCCESS =
  "FETCH_BUSINESSES_BY_USER_ID_SUCCESS";
export const FETCH_BUSINESSES_BY_USER_ID_FAIL =
  "FETCH_BUSINESSES_BY_USER_ID_FAIL";
export const FETCH_BUSINESSES_BY_ID_SUCCESS = "FETCH_BUSINESSES_BY_ID_SUCCESS";
export const FETCH_BUSINESSES_BY_ID_FAIL = "FETCH_BUSINESSES_BY_ID_FAIL";
export const SEARCH_BUSINESSES_SUCCESS = "SEARCH_BUSINESSES_SUCCESS";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
