export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ADD_RESPONSE_MESSAGE = 'ADD_RESPONSE_MESSAGE';
export const DELETE_RESPONSE_MESSAGE = 'DELETE_RESPONSE_MESSAGE';

// action types for business componet
export const FETCH_ALL_BUSINESSES_SUCCESS = 'FETCH_ALL_BUSINESSES_SUCCESS';
export const FETCH_ALL_BUSINESSES_FAIL = 'FETCH_ALL_BUSINESSES_FAIL';
export const FETCH_BUSINESSES_BY_USER_ID_SUCCESS = 'FETCH_BUSINESSES_BY_USER_ID_SUCCESS';
export const FETCH_BUSINESSES_BY_USER_ID_FAIL = 'FETCH_BUSINESSES_BY_USER_ID_FAIL';
export const FETCH_BUSINESSES_BY_ID_SUCCESS = 'FETCH_BUSINESSES_BY_ID_SUCCESS';
export const FETCH_BUSINESSES_BY_ID_FAIL = 'FETCH_BUSINESSES_BY_ID_FAIL';
export const DELETE_BUSINESS_SUCCESS = 'DELETE_BUSINESS_SUCCESS';
export const DELETE_BUSINESS_FAIL = 'DELETE_BUSINESS_FAIL';

// action types for reset password componet
export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS';
export const CONFIRM_EMAIL_FAIL = 'CONFIRM_EMAIL_FAIL';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
